vim9script

# &guifont = "CascadiaCode-Light:h11"
# &guifont = "FiraCode-Retina:h11"
# &guifont = "FiraCodeRoman-Regular:h11"
# &guifont = "JetBrainsMono-Regular:h14"
# &guifont = "FantasqueSansMono-Regular:h12"
# &guifont = "IBMPlexMono:h10"
&guifont = "RecMonoCasual-Regular:h16"

# Keep the system clipboard and the vim pasteboard separate. If this behaviour is not
# desired, set g:unify_clipboards to true.
if get(g:, 'unify_clipboards', false)
  if has('unnamedplus')
    set clipboard^=unnamedplus
  else
    set clipboard^=unnamed
  endif
else
  set clipboard&
endif

if has('gui_macvim')
  set antialias fuoptions=maxvert,maxhorz macligatures

  nmap <D-/> gcc
  xmap <D-/> gc
endif

set nomousefocus mousehide winaltkeys=no
