if !has('vim9script')
  finish
endif

vim9script

if !exists('g:hz_vim_config_version')
  g:hz_vim_config_version = '2024.0'
  lockvar g:hz_vim_config_version
endif

# chezmoi.vim must be loaded before `filetype plugin indent on`, `syntax enable`,
# or `syntax on`. https://github.com/alker0/chezmoi.vim?tab=readme-ov-file#install
try
  packadd chezmoi.vim
catch /^Vim\%((\a\+)\)\=:E919:/
endtry

# Import global and global-local options.
import './config/options.vim'

# Set `g:` variables, especially those required before plugins are loaded.
import './config/defaults.vim'

# Add plugins with packix (also auto-install packix)
import './config/plugins.vim'

# Setup display configuration
import './config/display.vim'

# Add key mappings
import './config/key_mappings.vim'

# Configure LSP
import './config/lsp.vim'

# Configure local autocommands that aren't specific to plugin behaviours.
import './config/autocmd.vim'

# Define abbreviations
import './config/abbreviations.vim'

# Define user commands
import './config/commands.vim'

# Define projectionist heuristics
import './config/projections.vim'

set secure
