scriptencoding utf-8

" Skip setup for vim-tiny/vim-small
if 0 | finish | endif

""
" 2021 Version of my vim configuration, starting from scratch.
if !exists('g:hz_vim_config_version')
  let g:hz_vim_config_version = '2021.0'
  lockvar g:hz_vim_config_version
endif

" Use vim settings. First because it changes other options as a side-effect.
" vint: -ProhibitSetNoCompatible
if has('vim_starting') | set nocompatible | endif
" vint: +ProhibitSetNoCompatible

" Add ./hz/ to the vim runtime path for autoloading function completion.
" if isdirectory(expand('$HOME/.vim'))
"   let g:hz_vim_root_path = expand('$HOME/.vim')
" elseif isdirectory(expand('$HOME/vimfiles'))
"   let g:hz_vim_root_path = expand('$HOME/vimfiles')
" end
" let &runtimepath = &runtimepath . printf(',%s/hz', g:hz_vim_root_path)

runtime config/init.vim
runtime config/packages.vim
runtime config/abbreviations.vim
runtime config/autocmd.vim
runtime config/commands.vim
" runtime config/filetype.vim
runtime config/keys.vim
"
runtime config/packages/config.vim

colorscheme quantum

" let g:afterglow_blackout=1
" let g:afterglow_italic_comments=1
" let g:afterglow_inherit_background=1
" silent! colorscheme afterglow
" silent! colorscheme alduin

" silent! colorscheme anderson
" silent! colorscheme angr

" let g:ayucolor="light"
" let g:ayucolor="mirage"
" let g:ayucolor="dark"
" silent! colorscheme ayu

" silent! colorscheme apprentice
" silent! colorscheme deep-space
silent! colorscheme deus

set secure
