scriptencoding utf-8

" Skip setup for vim-tiny/vim-small
if 0 | finish | endif

""
" 2021 Version of my vim configuration, starting from scratch.
if !exists('g:hz_vim_config_version')
  let g:hz_vim_config_version = '2023.0'
  lockvar g:hz_vim_config_version
endif

" Use vim settings. First because it changes other options as a side-effect.
" vint: -ProhibitSetNoCompatible
if has('vim_starting') | set nocompatible | endif
" vint: +ProhibitSetNoCompatible

" Load various initialization scripts. All of these should be loaded before
" packages are loaded, except the one below.
try
  packadd chezmoi.vim
catch /^Vim\%((\a\+)\)\=:E919:/
endtry

runtime config/defaults.vim
runtime config/plugins.vim
runtime config/abbreviations.vim
runtime config/commands.vim
runtime config/keys.vim
runtime config/plugins/config.vim

" colorscheme quantum
colorscheme evening

" let g:afterglow_blackout=1
" let g:afterglow_italic_comments=1
" let g:afterglow_inherit_background=1
" silent! colorscheme afterglow
" silent! colorscheme alduin

" silent! colorscheme anderson
" silent! colorscheme angr

" let g:ayucolor = "light"
" let g:ayucolor = "mirage"
" let g:ayucolor = "dark"
" silent! colorscheme ayu

" silent! colorscheme apprentice
" silent! colorscheme deep-space
" silent! colorscheme deus
silent! colorscheme penumbradark++

autocmd User DirenvLoaded normal lh

set secure
