# role: base
#
# The base role is applied to all systems. It does not need to be included in the roles
# list.
---
defrole:
  base:
    taps:
      # base/core
      homebrew/bundle:
      homebrew/services:

      # base/web
      browsers-software/tap:

    casks:
      # base/core
      alfred: Application launcher and productivity software
      cleanupbuddy: Clean keyboard and trackpad
      itsycal: Menu bar calendar
      jordanbaird-ice: Menu bar manager (Bartender alternative)
      leader-key: Application launcher
      loop: Window manager (Moom alternative)
      maccy: Clipboard manager (Paste alternative)
      meetingbar: Shows the next meeting in the menu bar
      obsidian: Knowledge base that works on top of a local folder of plain text Markdown files
      qlcolorcode: Quick Look plug-in that renders source code with syntax highlighting
      qlmarkdown: Quick Look generator for Markdown files
      qlstephen: Quick Look plugin for plaintext files without an extension
      qlvideo: Thumbnails, static previews, cover art and metadata for video files
      quicklook-json: Quick Look plugin for JSON files
      startupfolder: Run anything at startup by simply placing it in a special folder
      trex: Easy to use text extraction tool (TextSniper alternative)
      webpquicklook: Quick Look plugin for webp files
      xprocheck: Anti-malware scan logging tool

      # base/dev
      ghostty: Terminal emulator that uses platform-native UI and GPU acceleration
      hex-fiend: Hex editor focussing on speed
      imhex: Hex editor for reverse engineers
      macvim: Text editor

      # base/web
      browsers: Open the right browser at the right time
      finicky: Utility for customizing which browser to start
      firefox: Web browser
      safari-technology-preview: Web browser

    fonts:
      # base/core
      0xproto:
      cascadia-code:
      cascadia-mono:
      eb-garamond:
      fantasque-sans-mono:
      fira-code:
      hack:
      ia-writer-duo:
      ia-writer-mono:
      ia-writer-quattro:
      ibm-plex-mono:
      jetbrains-mono:
      juliamono:
      maple-mono:
      monaspace:
      sf-mono:
      source-code-pro:
      space-mono:
      zed-mono:

    mas:
      # base/core
      1569813296: 1Password for Safari

      # base/dev
      497799835: Xcode

      # base/web
      1440147259: AdGuard for Safari

    ports:
      install:
        # base/core
        1password-cli:
        atuin:
        chezmoi:
        fish:
        mas:
        mise:
        git: +credential_osxkeychain+diff_highlight+doc+pcre+perl5_34
        pam-reattach:

        # base/dev
        age:
        cargo:
        deno:
        difftastic:
        duf:
        dust:
        editorconfig-checker:
        eza: +doc+git
        fastmod:
        fd:
        fswatch:
        gawk:
        goawk:
        gojq:
        gh:
        git-absorb:
        git-delta:
        git-interactive-rebase-tool:
        gmake:
        go:
        hwatch:
        hyperfine:
        jujutsu:
        just:
        lazygit:
        lemmeknow:
        lychee:
        mani:
        moreutils: +doc
        ov:
        pv:
        shellcheck:
        shellharden:
        shfmt:
        tig: +doc
        tokei:
        typos:
        universal-ctags: +iconv+libxml2+link_to_ctags+manpages
        uv:
        zizmor:
        zoxide:

        # base/text
        ansifilter:
        antiword:
        bat-extras:
        bat:
        csvlens:
        ctpv:
        dos2unix:
        glow:
        gum:
        htmd-cli:
        ijq:
        jaq:
        jnv:
        jq:
        jqfmt:
        jqp:
        mdcat:
        ripgrep:
        taplo:

      setunrequested:
        # base/core
        ftgl:
        lima:
        openjdk11:
        openjdk17:
        rebels-in-the-sky:
        rlwrap:
        ruby-build:
        ruby-install:

    cond:
      # base/dev
      - if-stat: /Applications/Xcode.app
        ports:
          install:
            terminal-notifier:

      # base/web
      - if-role: personal
        mas:
          1601151613: Baking Soda
          1474335294: GoodLinks
          1619241039: History Book
          1544743900: Hush
          1507396839: Later
          1554029832: MarkDownload - Markdown Web Clipper
          1160374471: PiPifier
          1522267256: Shareful
          6471380298: StopTheMadness Pro
          1591303229: Vinegar

    uv:
      # base/text
      # Convert between CBOR, JSON, MessagePack, TOML, and YAML
      remarshal:

# vim: ft=yaml

