# Extra dev tools.
---
defrole:
  dev-extra:
    # TODO: These tools should be available in MacPorts, either through a mainline port or
    #       a "private" port that I maintain at halostatue/ports.
    formulae:
      csvtk: Cross-platform, efficient and practical CSV/TSV toolkit in Golang
      flarectl: CLI application for interacting with a Cloudflare account
      syft: CLI for generating a Software Bill of Materials from container images

    casks:
      livebook: Code notebooks for Elixir developers
      visual-studio-code: Open-source code editor
      zed: Multiplayer code editor

    ports:
      install:
        act:
        actionlint:
        cloc:
        prr:
        rust-script:
        git-branchless:
        git-mediate:
        git-some-extras:
        git-tools:
        scc:

    cond:
      - if-port: ftgl
        ports:
          install:
            gource:
      - if-port: openjdk17
        ports:
          install:
            pkl:

      - if-role: personal
        mas:
          1622145140: Codelime
          640199958: Developer
          439697913: Icon Slate
          992115977: Image2icon
          889428659: xScope

# vim: ft=yaml
