# role: llm
#
# The LLM role includes local or remote LLM-related software.
---
defrole:
  llm:
    casks:
      kiro: Agent-centric IDE with spec-driven development
      kiro-cli: AI-powered productivity tool for the command-line
      msty: Run LLMs locally
      ollamac: Interact with Ollama models

    ports:
      install:
        # apfel:
        # auge:
        # translate:

