# role: terraform
# Terraform-related tooling.
---
defrole:
  terraform:
    ports:
      install:
        pug:
        terraform-docs:
        terraformer:
        terramaid:
        tfmigrate:
        tfsec:
        tfupdate:

# vim: ft=yaml
