# role: work
#
# The work role includes software applicable to my work machines.
---
defrole:
  work:
    casks:
      bruno: Open source IDE for exploring and testing APIs
      drovio: Remote pair programming and team collaboration tool
      meld: Visual diff and merge tool
      slack: Team communication and collaboration software
      visualdiffer: Visually compare folders and files

    mas:
      1451685025: WireGuard

    ports:
      install:
        jwt-cli:
        oasdiff:
        oath-toolkit:
        oauth2c:
        redis:
