# role: work
#
# The work role includes software applicable to my work machines.
---
defrole:
  work:
    casks:
      bruno: Open source IDE for exploring and testing APIs
      cursor-cli: Command-line agent for Cursor
      cursor: Write, edit, and chat about your code with AI
      drovio: Remote pair programming and team collaboration tool
      meld: Visual diff and merge tool
      postman: Collaboration platform for API development
      slack: Team communication and collaboration software
      visualdiffer: Visually compare folders and files
      zen: Gecko based web browser

    mas:
      1451685025: WireGuard

    ports:
      install:
        jira-cli:
        jwt-cli:
        oasdiff:
        oath-toolkit:
        oauth2c:
        redis:

    vscode:
      42crunch.vscode-openapi:
