#! /usr/bin/env fish

code --install-extension asvetliakov.vscode-neovim
code --install-extension bpruitt-goddard.mermaid-markdown-syntax-highlighting
code --install-extension castwide.solargraph
code --install-extension dbaeumer.vscode-eslint
code --install-extension DotJoshJohnson.xml
code --install-extension dunstontc.viml
code --install-extension eamodio.gitlens
code --install-extension esbenp.prettier-vscode
code --install-extension gamunu.vscode-yarn
code --install-extension GitHub.vscode-pull-request-github
code --install-extension golang.go
code --install-extension HookyQR.beautify
code --install-extension Jacano.vscode-pnpm
code --install-extension KnisterPeter.vscode-github
code --install-extension mike-co.import-sorter
code --install-extension mikestead.dotenv
code --install-extension Prisma.prisma
code --install-extension rebornix.ruby
code --install-extension rust-lang.rust-analyzer
code --install-extension statiolake.vscode-rustfmt
code --install-extension svelte.svelte-vscode
code --install-extension tamasfe.even-better-toml
code --install-extension testdouble.standard
code --install-extension usernamehw.errorlens
code --install-extension vscode-icons-team.vscode-icons
code --install-extension vstirbu.vscode-mermaid-preview
code --install-extension wingrunr21.vscode-ruby
code --install-extension ZixuanChen.vitest-explorer
