'$schema' = 'https://starship.rs/config-schema.json'

add_newline = true
continuation_prompt = '[▸▹ ](dimmed white)'

right_format = ''

scan_timeout = 30
command_timeout = 500
palette = 'catppuccin_mocha'
follow_symlinks = true

# put $cmd_duration *after* $line_break, before $character

format = """
$hostname\
$localip\
$shlvl\
$directory\
$singularity\
\
$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
\
$kubernetes\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$gleam\
$golang\
$nix_shell\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$zig\
$buf\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$nats\
$direnv\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$time\
$status\
$os\
$container\
$shell\
$character
"""

battery.disabled = true
direnv.disabled = true
docker_context.disabled = true
package.disabled = true
username.disabled = true
vagrant.disabled = true

[aws]
format = '(\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\])'


[buf]
format = '(\[[$symbol$version]($style)\])'

[bun]
format = '(\[[$symbol($version)]($style)\])'

[c]
format = '(\[[$symbol($version(-$name))]($style)\])'

[character]
error_symbol = '[✖](red)'

[cmake]
format = '(\[[$symbol($version)]($style)\])'

[cmd_duration]
format = '(\[[⏱ $duration]($style)\])'

[cobol]
format = '(\[[$symbol($version)]($style)\])'

[conda]
format = '(\[[$symbol$environment]($style)\])'

[container]
format = '([$symbol [$name] ]($style))'

[crystal]
format = '(\[[$symbol($version)]($style)\])'

[daml]
format = '(\[[$symbol($version)]($style)\])'

[dart]
format = '(\[[$symbol($version)]($style)\])'

[deno]
format = '(\[[$symbol($version)]($style)\])'

[directory]
truncation_symbol = '…/'

[dotnet]
format = '(\[[$symbol($version)(🎯 $tfm)]($style)\])'

[elixir]
format = '(\[[$symbol($version \(OTP $otp_version\))]($style)\])'

[elm]
format = '(\[[$symbol($version)]($style)\])'

[erlang]
format = '(\[[$symbol($version)]($style)\])'
symbol = 'ⓔ '

[fennel]
format = '(\[[$symbol($version)]($style)\])'

[fill]
symbol = ' '

[fossil_branch]
format = '(\[[$symbol$branch]($style)\])'
disabled = false

[fossil_metrics]
disabled = false

[gcloud]
format = '(\[[$symbol$account(@$domain)(\($region\))]($style)\])'

[git_branch]
format = '(\[[$symbol$branch]($style)\])'

[git_commit]
commit_hash_length = 9

[git_metrics]
disabled = false
format = '([+$added]($added_style))([-$deleted]($deleted_style))'

[git_status]
format = '(([\[$all_status$ahead_behind\]]($style)))'

[gleam]
format = '(\[[$symbol($version)]($style)\])'

[golang]
format = '(\[[$symbol($version)]($style)\])'

[gradle]
format = '(\[[$symbol($version)]($style)\])'

[guix_shell]
format = '(\[[$symbol]($style)\])'

[haskell]
format = '(\[[$symbol($version)]($style)\])'

[haxe]
format = '(\[[$symbol($version)]($style)\])'

[helm]
format = '(\[[$symbol($version)]($style)\])'

[hg_branch]
disabled = false
format = '(\[[$symbol$branch]($style)\])'

[java]
format = '(\[[$symbol($version)]($style)\])'

[julia]
format = '(\[[$symbol($version)]($style)\])'

[kotlin]
format = '(\[[$symbol($version)]($style)\])'

[kubernetes]
format = '(\[[$symbol$context( \($namespace\))]($style)\])'
disabled = false

[lua]
format = '(\[[$symbol($version)]($style)\])'

[memory_usage]
format = '(\[$symbol[$ram( | $swap)]($style)\])'

[meson]
format = '(\[[$symbol$project]($style)\])'

[nim]
format = '(\[[$symbol($version)]($style)\])'

[nix_shell]
format = '(\[[$symbol$state( \($name\))]($style)\])'

[nodejs]
format = '(\[[$symbol($version)]($style)\])'
symbol = '[⬢](bold green) '

[ocaml]
format = '(\[[$symbol($version)(\($switch_indicator$switch_name\))]($style)\])'

[opa]
format = '(\[[$symbol($version)]($style)\])'

[openstack]
format = '(\[[$symbol$cloud(\($project\))]($style)\])'

[perl]
format = '(\[[$symbol($version)]($style)\])'

[php]
format = '(\[[$symbol($version)]($style)\])'

[pijul_channel]
disabled = false
format = '(\[[$symbol$channel]($style)\])'

[pulumi]
format = '(\[[$symbol$stack]($style)\])'
symbol = '🧊 '

[purescript]
symbol = '⪋ '
format = '(\[[$symbol($version)]($style)\])'

[python]
format = '(\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\])'

[quarto]
format = '(\[[$symbol($version)]($style)\])'

[raku]
format = '(\[[$symbol($version-$vm_version)]($style)\])'

[red]
format = '(\[[$symbol($version)]($style)\])'

[rlang]
format = '(\[[$symbol($version)]($style)\])'

[ruby]
format = '(\[[$symbol($version)]($style)\])'

[rust]
format = '(\[[$symbol($version)]($style)\])'

[scala]
format = '(\[[$symbol($version)]($style)\])'

[singularity]
format = '(([$symbol[$env] ]($style)))'

[solidity]
format = '(\[[$symbol($version)]($style)\])'

[spack]
format = '(\[[$symbol$environment]($style)\])'

[swift]
format = '(\[[$symbol($version)]($style)\])'

[terraform]
format = '(\[[$symbol$workspace]($style)\])'

[typst]
format = '(([$symbol($version )]($style)))'
symbol = 't '

[vlang]
format = '(\[[$symbol($version)]($style)\])'

[zig]
format = '(\[[$symbol($version)]($style)\])'

[palettes.catppuccin_mocha]
rosewater = '#f5e0dc'
flamingo = '#f2cdcd'
pink = '#f5c2e7'
mauve = '#cba6f7'
red = '#f38ba8'
maroon = '#eba0ac'
peach = '#fab387'
yellow = '#f9e2af'
green = '#a6e3a1'
teal = '#94e2d5'
sky = '#89dceb'
sapphire = '#74c7ec'
blue = '#89b4fa'
lavender = '#b4befe'
text = '#cdd6f4'
subtext1 = '#bac2de'
subtext0 = '#a6adc8'
overlay2 = '#9399b2'
overlay1 = '#7f849c'
overlay0 = '#6c7086'
surface2 = '#585b70'
surface1 = '#45475a'
surface0 = '#313244'
base = '#1e1e2e'
mantle = '#181825'
crust = '#11111b'
