'$schema' = 'https://starship.rs/config-schema.json'

add_newline = true
continuation_prompt = "[▸▹ ](dimmed white)"

right_format = ''

scan_timeout = 30
command_timeout = 500
palette = 'catppuccin_mocha'
follow_symlinks = true

# put $cmd_duration *after* $line_break, before $character

format = "$all"

[aws]
format = '(\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\])'

[azure]
disabled = true
format = '(\[[$symbol($subscription)]($style)\])'
symbol = '󰠅 '

[battery]
disabled = true
full_symbol = '• '
charging_symbol = '⇡ '
discharging_symbol = '⇣ '
unknown_symbol = '❓ '
empty_symbol = '❗ '

[buf]
format = '(\[[$symbol$version]($style)\])'

[bun]
format = '(\[[$symbol($version)]($style)\])'

[c]
format = '(\[[$symbol($version(-$name))]($style)\])'

[character]
format = "$symbol "
error_symbol = "[✖](italic red)"
vimcmd_symbol = "[■](italic dimmed green)"
# not supported in zsh
vimcmd_replace_one_symbol = "◌"
vimcmd_replace_symbol = "□"
vimcmd_visual_symbol = "▼"

[cmake]
format = '(\[[$symbol($version)]($style)\])'

[cmd_duration]
format = '(\[[⏱ $duration]($style)\])'

[cobol]
format = '(\[[$symbol($version)]($style)\])'

[conda]
format = '(\[[$symbol$environment]($style)\])'

[container]
format = '([$symbol [$name] ]($style))'

[crystal]
format = '(\[[$symbol($version)]($style)\])'

[daml]
format = '(\[[$symbol($version)]($style)\])'

[dart]
format = '(\[[$symbol($version)]($style)\])'

[deno]
format = '(\[[$symbol($version)]($style)\])'

[docker_context]
# disabled = true
format = '(\[[$symbol$context]($style)\])'

[dotnet]
format = '(\[[$symbol($version)(🎯 $tfm)]($style)\])'

[elixir]
format = '(\[[$symbol($version \(OTP $otp_version\))]($style)\])'

[elm]
format = '(\[[$symbol($version)]($style)\])'

[erlang]
format = '(\[[$symbol($version)]($style)\])'
symbol = 'ⓔ '

[fennel]
format = '(\[[$symbol($version)]($style)\])'

[fossil_branch]
format = '(\[[$symbol$branch]($style)\])'
disabled = false

[fossil_metrics]
disabled = false

[gcloud]
format = '(\[[$symbol$account(@$domain)(\($region\))]($style)\])'

[git_branch]
format = '(\[[$symbol$branch]($style)\])'

[git_commit]
commit_hash_length = 9

[git_metrics]
disabled = false

[git_status]
format = '(([\[$all_status$ahead_behind\]]($style)))'

[gleam]
format = '(\[[$symbol($version)]($style)\])'

[golang]
format = '(\[[$symbol($version)]($style)\])'

[gradle]
format = '(\[[$symbol($version)]($style)\])'

[guix_shell]
format = '(\[[$symbol]($style)\])'

[haskell]
format = '(\[[$symbol($version)]($style)\])'

[haxe]
format = '(\[[$symbol($version)]($style)\])'

[helm]
format = '(\[[$symbol($version)]($style)\])'

[hg_branch]
format = '(\[[$symbol$branch]($style)\])'

[java]
format = '(\[[$symbol($version)]($style)\])'

[julia]
format = '(\[[$symbol($version)]($style)\])'

[kotlin]
format = '(\[[$symbol($version)]($style)\])'

[kubernetes]
format = '(\[[$symbol$context( \($namespace\))]($style)\])'
disabled = false

[lua]
format = '(\[[$symbol($version)]($style)\])'

[memory_usage]
format = '(\[$symbol[$ram( | $swap)]($style)\])'

[meson]
format = '(\[[$symbol$project]($style)\])'

[nim]
format = '(\[[$symbol($version)]($style)\])'

[nix_shell]
format = '(\[[$symbol$state( \($name\))]($style)\])'

[nodejs]
format = '(\[[$symbol($version)]($style)\])'
symbol = '[⬢](bold green) '

[ocaml]
format = '(\[[$symbol($version)(\($switch_indicator$switch_name\))]($style)\])'

[opa]
format = '(\[[$symbol($version)]($style)\])'

[openstack]
format = '(\[[$symbol$cloud(\($project\))]($style)\])'

[os]
format = '(\[[$symbol]($style)\])'

[package]
disabled = true
format = '(\[[$symbol$version]($style)\])'

[perl]
format = '(\[[$symbol($version)]($style)\])'

[php]
format = '(\[[$symbol($version)]($style)\])'

[pijul_channel]
disabled = false
format = '(\[[$symbol$channel]($style)\])'

[pulumi]
format = '(\[[$symbol$stack]($style)\])'
symbol = '🧊 '

[purescript]
format = '(\[[$symbol($version)]($style)\])'

[python]
format = '(\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\])'

[quarto]
format = '(\[[$symbol($version)]($style)\])'

[raku]
format = '(\[[$symbol($version-$vm_version)]($style)\])'

[red]
format = '(\[[$symbol($version)]($style)\])'

[rlang]
format = '(\[[$symbol($version)]($style)\])'

[ruby]
format = '(\[[$symbol($version)]($style)\])'

[rust]
format = '(\[[$symbol($version)]($style)\])'

[scala]
format = '(\[[$symbol($version)]($style)\])'

[singularity]
format = '(([$symbol[$env] ]($style)))'

[solidity]
format = '(\[[$symbol($version)]($style)\])'

[spack]
format = '(\[[$symbol$environment]($style)\])'

[sudo]
format = '([$symbol]($style))'
style = 'bold italic bright-purple'
symbol = '⋈┈'

[status]
format = '(([$symbol$status ]($style)))'

[swift]
format = '(\[[$symbol($version)]($style)\])'

[terraform]
format = '(\[[$symbol$workspace]($style)\])'

[time]
format = '(\[[$time]($style)\])'

[typst]
format = '(([$symbol($version )]($style)))'
symbol = 't '

[username]
format = '(\[[$user]($style)\])'

[vagrant]
disabled = true
format = '(\[[$symbol($version)]($style)\])'

[vlang]
format = '(\[[$symbol($version)]($style)\])'

[zig]
format = '(\[[$symbol($version)]($style)\])'

[palettes.catppuccin_mocha]
rosewater = '#f5e0dc'
flamingo = '#f2cdcd'
pink = '#f5c2e7'
mauve = '#cba6f7'
red = '#f38ba8'
maroon = '#eba0ac'
peach = '#fab387'
yellow = '#f9e2af'
green = '#a6e3a1'
teal = '#94e2d5'
sky = '#89dceb'
sapphire = '#74c7ec'
blue = '#89b4fa'
lavender = '#b4befe'
text = '#cdd6f4'
subtext1 = '#bac2de'
subtext0 = '#a6adc8'
overlay2 = '#9399b2'
overlay1 = '#7f849c'
overlay0 = '#6c7086'
surface2 = '#585b70'
surface1 = '#45475a'
surface0 = '#313244'
base = '#1e1e2e'
mantle = '#181825'
crust = '#11111b'
